### ISSUE TITLE
KeyError retrieving accounts

### ISSUE THREAD

**Issue by pantherale0** [JakeMartin-ICL/monzopy#3]
Hi,

Not sure if I've just got some bad luck lol. However the HA integration has stopped working entirely for me now.

```This error originated from a custom integration.

Logger: custom_components.monzo
Source: helpers/update_coordinator.py:354
integration: Monzo
First occurred: 10:15:19 (3 occurrences)
Last logged: 10:15:34

Unexpected error fetching monzo data
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/monzopy/monzopy.py", line 130, in _get_accounts
    for acc in res["accounts"]:
               ~~~^^^^^^^^^^^^
KeyError: 'accounts'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 271, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/monzo/__init__.py", line 73, in async_get_monzo_api_data
    accounts = await externalapi.user_account.accounts()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/monzopy/monzopy.py", line 90, in accounts
    accounts = await self._get_accounts()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/monzopy/monzopy.py", line 135, in _get_accounts
    raise InvalidMonzoAPIResponseError
monzopy.monzopy.InvalidMonzoAPIResponseError
```

I've put this here because the error seems to come from the python module rather than the HA integration itself and the assumption that the variable 'res' contains `accounts`. Perhaps a validation check first to prevent the KeyError?

```
if "accounts" not in res:
    # error here
```

**Comment by JakeMartin-ICL** [comment]
That bit of code is already in a try-catch for `KeyError`:

https://github.com/JakeMartin-ICL/monzopy/blob/212144b5e36ab9a34b95884830b7e9f996cc49f1/monzopy/monzopy.py#L133-L139

This then passes the response on to check whether it's due to the authorisation expiring or something else, and in this case it seems to be something else, so we're intentionally raising the InvalidMonzoAPIResponseError as there's not much else that can be done in this situation.

Ideally, we should find out what exactly Monzo is returning by either:

- Using the playground like you did on https://github.com/JakeMartin-ICL/ha-monzo/issues/7 (though this might not reveal the issue if what we're getting back is some unexpected auth error) - probably best to try this first anyway
- Debugging home assistant locally yourself and putting a breakpoint so we can see the exact response your instance is getting
- Waiting for me to improve logging. I should be able to pass the response up to Home Assistant so it'll get logged, but I might not get around to this this weekend.

**Comment by pantherale0** [comment]
Thanks, sorry it's taken a while to get back.

I've tested the accounts endpoint and it seems to be returning a valid response:

```
{"accounts": [...]}
```

I did try to debug the module / integration but they seem to be tightly connected so I haven't been able to get the module to run without the integration.
